### ISSUE TITLE
Octupus should be extended to match the additional environmetns

### ISSUE THREAD

**Issue by Bagaboo** [collector-bank/savings-template#19]
MIGR and ACC do not exist in Octopus as of now. 

They should be added and configured to enable deployment to them according to the following life cycles:

LifeCycles
Default: DEV->UAT->PROD
Extraordinary: Right to PROD (is to be removed)
Migration: Right to MIGR
Accelerated: Right to ACC

**Comment by perjahn** [comment]
done.

**Comment by Bagaboo** [comment]
I can't see the environments and corresponding variables. 
Am i missing something?

**Comment by perjahn** [comment]
Fixed.

**Comment by Bagaboo** [comment]
Excellent.
